---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: p-mysql
  type: pivnet
  source:
    api_token: my-api-token
    product_slug: p-mysql

jobs:
- name: create-p-mysql-pivnet
  plan:
  - put: p-mysql
    params:
      metadata_file: relative/path/to/some-metadata-file
      file_glob: relative/path/to/some-source-files/*
